# Generated by Django 3.1.2 on 2020-12-02 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Team', models.CharField(max_length=30)),
                ('Away_Team', models.CharField(max_length=30)),
                ('date_played', models.DateField(blank=True, default=datetime.datetime.today)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
            ],
        ),
    ]
